// xconfgen renders a typed Go config struct + Load wrapper from an xconf
// schema variable. Intended to be invoked via //go:generate.
//
// Usage:
//
//	//go:generate xconfgen -type AppConfig
//
// Flags:
//
//	-pkg     Import path of the package that declares the schema variable.
//	         Default: "." (the package containing the go:generate directive).
//	-var     Schema variable name. Default: "Schema".
//	-type    Root Go type name. Required.
//	-out     Output file path. Default: "<lower(type)>_gen.go" in the
//	         schema package's directory.
//	-loadfn  Name of the generated Load function. Default: "Load".
//
// Internally xconfgen writes a temporary main.go inside the user's module
// that imports the schema package and invokes pkg/codegen.Render. The
// temporary directory is removed after rendering.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	pkg := flag.String("pkg", ".", "import path of schema package")
	varName := flag.String("var", "Schema", "schema variable name")
	typeName := flag.String("type", "", "root Go type name (required)")
	outPath := flag.String("out", "", "output file path")
	loadFn := flag.String("loadfn", "Load", "name of generated load function")
	flag.Parse()

	if *typeName == "" {
		fatal("missing required -type flag")
	}
	if err := run(*pkg, *varName, *typeName, *outPath, *loadFn); err != nil {
		fatal(err.Error())
	}
}

func run(pkgPath, varName, typeName, outPath, loadFn string) error {
	info, err := resolvePackage(pkgPath)
	if err != nil {
		return fmt.Errorf("resolve %s: %w", pkgPath, err)
	}

	if outPath == "" {
		outPath = filepath.Join(info.Dir, strings.ToLower(typeName)+"_gen.go")
	}

	tmpDir, err := os.MkdirTemp(info.Dir, "xconfgen-")
	if err != nil {
		return fmt.Errorf("mkdir tmp: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	mainSrc := renderTmpMain(info.ImportPath, info.Name, varName, typeName, loadFn)
	tmpMain := filepath.Join(tmpDir, "main.go")
	if err := os.WriteFile(tmpMain, []byte(mainSrc), 0600); err != nil {
		return fmt.Errorf("write tmp main: %w", err)
	}

	out, err := goRun(tmpDir)
	if err != nil {
		return fmt.Errorf("go run codegen: %w", err)
	}

	if err := os.WriteFile(outPath, out, 0600); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	fmt.Fprintf(os.Stderr, "xconfgen: wrote %s\n", outPath)
	return nil
}

type pkgInfo struct {
	ImportPath string `json:"ImportPath"`
	Dir        string `json:"Dir"`
	Name       string `json:"Name"`
}

func resolvePackage(pkgPath string) (*pkgInfo, error) {
	cmd := exec.Command("go", "list", "-json", pkgPath)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return nil, err
	}
	var info pkgInfo
	if err := json.Unmarshal(out.Bytes(), &info); err != nil {
		return nil, fmt.Errorf("parse go list output: %w", err)
	}
	if info.ImportPath == "" || info.Dir == "" {
		return nil, fmt.Errorf("go list returned empty fields")
	}
	return &info, nil
}

func renderTmpMain(importPath, pkgName, varName, typeName, loadFn string) string {
	return fmt.Sprintf(`// Auto-generated by xconfgen; do not edit.
package main

import (
	"os"

	target %q
	"github.com/gopherex/xconf/pkg/codegen"
)

func main() {
	if err := codegen.Render(os.Stdout, codegen.Options{
		Package:    %q,
		Schema:     target.%s,
		TypeName:   %q,
		SchemaExpr: %q,
		LoadFunc:   %q,
	}); err != nil {
		panic(err)
	}
}
`, importPath, pkgName, varName, typeName, varName, loadFn)
}

func goRun(dir string) ([]byte, error) {
	cmd := exec.Command("go", "run", ".")
	cmd.Dir = dir
	var out, errBuf bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("%w\n%s", err, errBuf.String())
	}
	return out.Bytes(), nil
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "xconfgen:", msg)
	os.Exit(1)
}
