// Package codegen renders typed Go source for an xconf schema.
//
// The rendered file contains:
//   - One struct type per Group node (the root group and any nested groups
//     that are not bound to an external type via GroupAs[T]).
//   - A Load(sources ...load.Source) wrapper that delegates to the runtime
//     loader using the source-of-truth Schema variable.
//
// Bindings:
//   - Group nodes with a BindType reuse the external Go type directly
//     (no nested struct is emitted); the external package is imported.
//   - Group nodes without a BindType produce a nested struct named after
//     the group; the root group's name is overridden via Options.TypeName.
package codegen

import (
	"fmt"
	"go/format"
	"io"
	"sort"
	"strings"

	"github.com/gopherex/xconf"
)

// Options controls Render.
type Options struct {
	// Package is the package clause for the generated file. Must match the
	// package that owns the schema variable.
	Package string

	// Schema is the schema to render.
	Schema *xconf.Schema

	// TypeName is the name of the root Go type (e.g. "AppConfig").
	TypeName string

	// SchemaExpr is the Go expression that refers to the schema variable
	// from within the generated file. For schemas declared in the same
	// package as the generated file, this is just the var name (default
	// "Schema").
	SchemaExpr string

	// LoadFunc is the name of the wrapper load function (default "Load").
	LoadFunc string
}

// Render writes the generated Go source to w.
func Render(w io.Writer, opts Options) error {
	if opts.Schema == nil {
		return fmt.Errorf("codegen: nil Schema")
	}
	if opts.Package == "" {
		return fmt.Errorf("codegen: empty Package")
	}
	if opts.TypeName == "" {
		opts.TypeName = "Config"
	}
	if opts.SchemaExpr == "" {
		opts.SchemaExpr = "Schema"
	}
	if opts.LoadFunc == "" {
		opts.LoadFunc = "Load"
	}

	r := &renderer{imports: map[string]string{}}
	r.addImport("github.com/gopherex/xconf/pkg/load", "")

	root := opts.Schema.Describe()
	if root.Kind != xconf.KindGroup {
		return fmt.Errorf("codegen: schema root must be a group, got %v", root.Kind)
	}
	rootDef, err := r.walkGroup(root, opts.TypeName)
	if err != nil {
		return err
	}

	const importsPlaceholder = "__XCONF_IMPORTS_PLACEHOLDER__"

	var body strings.Builder
	body.WriteString("// Code generated by xconfgen. DO NOT EDIT.\n\n")
	body.WriteString("package " + opts.Package + "\n\n")
	body.WriteString(importsPlaceholder + "\n")
	for _, sd := range r.structs {
		body.WriteString(sd.render())
		body.WriteString("\n")
	}
	body.WriteString(renderLoadFunc(opts, rootDef, r.loaderCalls))
	body.WriteString("\n")
	body.WriteString(r.renderLoadFromEnv(opts, rootDef, root))

	if r.needsOS {
		r.addImport("os", "")
	}
	if r.needsStrconv {
		r.addImport("strconv", "")
	}
	if r.needsStrings {
		r.addImport("strings", "")
	}
	if r.needsTime {
		r.addImport("time", "")
	}
	final := strings.Replace(body.String(), importsPlaceholder, r.renderImports(), 1)
	body.Reset()
	body.WriteString(final)

	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		// Emit unformatted source as a fallback so callers can inspect.
		_, _ = w.Write([]byte(body.String()))
		return fmt.Errorf("codegen: gofmt: %w", err)
	}
	_, err = w.Write(formatted)
	return err
}

// ---------------------------------------------------------------------------
// internals
// ---------------------------------------------------------------------------

type renderer struct {
	imports     map[string]string // path -> alias ("" = default)
	structs     []structDef
	loaderCalls []loaderCall

	// Flags toggled by the env-loader emitter so we can add stdlib imports
	// without scanning the emitted source.
	needsOS      bool
	needsStrconv bool
	needsStrings bool
	needsTime    bool
}

// loaderCall describes a BindLoader site: "cfg.<FieldName>, err = <LoaderRef>()"
// emitted inside the generated Load wrapper.
type loaderCall struct {
	FieldName string
	LoaderRef string
}

type structDef struct {
	Name   string
	Fields []structField
}

type structField struct {
	Name string
	Type string
}

func (s structDef) render() string {
	var b strings.Builder
	fmt.Fprintf(&b, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(&b, "\t%s %s\n", f.Name, f.Type)
	}
	b.WriteString("}\n")
	return b.String()
}

func (r *renderer) addImport(path, alias string) {
	if path == "" {
		return
	}
	if _, ok := r.imports[path]; !ok {
		r.imports[path] = alias
	}
}

func (r *renderer) renderImports() string {
	if len(r.imports) == 0 {
		return ""
	}
	paths := make([]string, 0, len(r.imports))
	for p := range r.imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range paths {
		alias := r.imports[p]
		if alias != "" {
			fmt.Fprintf(&b, "\t%s %q\n", alias, p)
		} else {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
	}
	b.WriteString(")\n")
	return b.String()
}

// walkGroup builds a struct definition for a Group node and returns the Go
// type expression to use when referring to it (for fields in a parent group).
// Side-effect: if the group has a BindLoader, register the loader call site
// so renderLoadFunc can emit a delegated init in the generated Load wrapper.
func (r *renderer) walkGroup(g xconf.FieldDesc, typeName string) (string, error) {
	// External type binding: do not emit a struct; reference the existing type.
	if g.BindType != "" {
		pkg, name, err := splitQualified(g.BindType)
		if err != nil {
			return "", err
		}
		r.addImport(pkg, "")
		if g.BindLoader != "" {
			lpkg, lname, err := splitQualified(g.BindLoader)
			if err != nil {
				return "", err
			}
			r.addImport(lpkg, "")
			r.loaderCalls = append(r.loaderCalls, loaderCall{
				FieldName: g.Name, // populated by caller via parent context — see fieldType
				LoaderRef: lastSegment(lpkg) + "." + lname,
			})
		}
		return lastSegment(pkg) + "." + name, nil
	}

	def := structDef{Name: typeName}
	for _, child := range g.Children {
		fieldType, err := r.fieldType(child, typeName+child.Name)
		if err != nil {
			return "", err
		}
		def.Fields = append(def.Fields, structField{Name: child.Name, Type: fieldType})
	}
	r.structs = append(r.structs, def)
	return typeName, nil
}

func (r *renderer) fieldType(d xconf.FieldDesc, nestedName string) (string, error) {
	switch d.Kind {
	case xconf.KindGroup:
		return r.walkGroup(d, nestedName)
	case xconf.KindDuration, xconf.KindTime:
		r.addImport("time", "")
		return d.GoType, nil
	default:
		return d.GoType, nil
	}
}

func renderLoadFunc(opts Options, rootType string, loaders []loaderCall) string {
	var loaderBlock strings.Builder
	for _, lc := range loaders {
		fmt.Fprintf(&loaderBlock,
			"\tif loaded, err := %s(); err != nil {\n\t\treturn nil, err\n\t} else {\n\t\tcfg.%s = *loaded\n\t}\n",
			lc.LoaderRef, lc.FieldName)
	}
	return fmt.Sprintf(`// %s fills a %s from the given sources by delegating to the runtime loader.
//
// Source priority: later sources override earlier ones; the schema's declared
// defaults lose to any source hit. After source-based load, any groups with
// a BindLoader are populated by calling the bound loader (its result wins).
func %s(sources ...load.Source) (*%s, error) {
	cfg := &%s{}
	if err := load.Load(%s, cfg, sources...); err != nil {
		return nil, err
	}
%s	return cfg, nil
}
`, opts.LoadFunc, rootType, opts.LoadFunc, rootType, rootType, opts.SchemaExpr, loaderBlock.String())
}

// splitQualified splits "github.com/foo/bar.Type" into ("github.com/foo/bar", "Type").
func splitQualified(qn string) (pkg, name string, err error) {
	idx := strings.LastIndex(qn, ".")
	if idx < 0 {
		return "", "", fmt.Errorf("codegen: bad qualified name %q", qn)
	}
	return qn[:idx], qn[idx+1:], nil
}

func lastSegment(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}
	return path
}
