package codegen_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/gopherex/xconf"
	"github.com/gopherex/xconf/example/app"
	"github.com/gopherex/xconf/pkg/codegen"
)

func TestRenderAppSchema(t *testing.T) {
	var buf bytes.Buffer
	err := codegen.Render(&buf, codegen.Options{
		Package:  "app",
		Schema:   app.Schema,
		TypeName: "AppConfig",
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	src := buf.String()

	wantContains := []string{
		"// Code generated by xconfgen. DO NOT EDIT.",
		"package app",
		`"github.com/gopherex/xconf/example/redislib"`,
		`"github.com/gopherex/xconf/pkg/load"`,
		"type AppConfig struct {",
		"Port         int",
		"DSN          string",
		"AllowedHosts []string",
		"RateLimits   map[string]int",
		"Redis        redislib.Config",
		"func Load(sources ...load.Source) (*AppConfig, error)",
		"load.Load(Schema, cfg, sources...)",
	}
	for _, w := range wantContains {
		if !strings.Contains(src, w) {
			t.Errorf("missing %q in output:\n%s", w, src)
		}
	}

	// Crucially: a bound-type group must NOT cause us to emit a duplicate
	// nested struct for Redis.
	if strings.Contains(src, "type Redis struct") || strings.Contains(src, "type AppConfigRedis struct") {
		t.Errorf("unexpected nested struct for bound Redis group:\n%s", src)
	}
}

type extCfg struct{ X int }

func extLoader() (*extCfg, error) { return &extCfg{X: 1}, nil }

func TestRenderBindLoader(t *testing.T) {
	sub := xconf.WithLoader(
		xconf.GroupAs[extCfg]("Ext", xconf.Int("X")),
		extLoader,
	)
	schema := xconf.Define("Root",
		xconf.Embed("Ext", sub),
	)
	var buf bytes.Buffer
	if err := codegen.Render(&buf, codegen.Options{
		Package: "gen", Schema: schema, TypeName: "Root",
	}); err != nil {
		t.Fatalf("render: %v", err)
	}
	src := buf.String()
	for _, w := range []string{
		"if loaded, err := codegen_test.extLoader(); err != nil",
		"cfg.Ext = *loaded",
		"if loaded, lerr := codegen_test.extLoader(); lerr != nil",
	} {
		if !strings.Contains(src, w) {
			t.Errorf("missing %q in:\n%s", w, src)
		}
	}
}

func TestRenderInlineGroupAndTime(t *testing.T) {
	schema := xconf.Define("ServerConfig",
		xconf.Duration("Timeout"),
		xconf.Group("HTTP",
			xconf.Int("Port"),
			xconf.String("Host"),
		),
	)
	var buf bytes.Buffer
	err := codegen.Render(&buf, codegen.Options{
		Package: "server", Schema: schema, TypeName: "ServerConfig",
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	src := buf.String()

	for _, w := range []string{
		`"time"`,
		"type ServerConfig struct {",
		"Timeout time.Duration",
		"HTTP    ServerConfigHTTP",
		"type ServerConfigHTTP struct {",
		"Port int",
		"Host string",
	} {
		if !strings.Contains(src, w) {
			t.Errorf("missing %q in:\n%s", w, src)
		}
	}
}
