package load_test

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"

	"github.com/gopherex/xconf"
	"github.com/gopherex/xconf/example/app"
	"github.com/gopherex/xconf/example/redislib"
	"github.com/gopherex/xconf/pkg/load"
	"github.com/gopherex/xconf/pkg/validate"
)

// AppConfig is generated by xconfgen from app.Schema; we import it directly.
type AppConfig = app.AppConfig

// Ensure redislib import stays referenced (used inside AppConfig.Redis).
var _ = redislib.Config{}

func baseEnv() map[string]string {
	return map[string]string{
		"DB_DSN": "postgres://localhost/x",
	}
}

func TestLoadDefaults(t *testing.T) {
	var cfg AppConfig
	if err := load.Load(app.Schema, &cfg, load.FromEnv(baseEnv())); err != nil {
		t.Fatalf("load: %v", err)
	}
	if cfg.Port != 8080 {
		t.Errorf("Port default lost: %d", cfg.Port)
	}
	if cfg.DSN != "postgres://localhost/x" {
		t.Errorf("DSN: %q", cfg.DSN)
	}
	if cfg.Redis.Addr != "localhost:6379" {
		t.Errorf("Redis.Addr default lost: %q", cfg.Redis.Addr)
	}
	if cfg.Redis.Timeout != 5*time.Second {
		t.Errorf("Redis.Timeout: %v", cfg.Redis.Timeout)
	}
}

func TestLoadFromMap(t *testing.T) {
	var cfg AppConfig
	data := map[string]any{
		"Port":         9090,
		"DSN":          "postgres://map/x",
		"AllowedHosts": []any{"a.example.com", "b.example.com"},
		"RateLimits":   map[string]any{"read": 100, "write": 50},
		"Redis": map[string]any{
			"Addr": "redis:6379",
			"DB":   3,
		},
	}
	if err := load.Load(app.Schema, &cfg, load.FromMap(data)); err != nil {
		t.Fatalf("load: %v", err)
	}
	if cfg.Port != 9090 || cfg.DSN != "postgres://map/x" {
		t.Errorf("scalars: %+v", cfg)
	}
	want := []string{"a.example.com", "b.example.com"}
	if !reflect.DeepEqual(cfg.AllowedHosts, want) {
		t.Errorf("AllowedHosts: %v", cfg.AllowedHosts)
	}
	if cfg.RateLimits["read"] != 100 || cfg.RateLimits["write"] != 50 {
		t.Errorf("RateLimits: %v", cfg.RateLimits)
	}
	if cfg.Redis.Addr != "redis:6379" || cfg.Redis.DB != 3 {
		t.Errorf("Redis: %+v", cfg.Redis)
	}
}

func TestEnvOverridesMap(t *testing.T) {
	data := map[string]any{
		"Port": 9090,
		"Redis": map[string]any{
			"Addr": "from-file:6379",
		},
	}
	envs := baseEnv()
	envs["PORT"] = "7000"
	envs["REDIS_ADDR"] = "from-env:6379"

	var cfg AppConfig
	err := load.Load(app.Schema, &cfg,
		load.FromMap(data),
		load.FromEnv(envs),
	)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if cfg.Port != 7000 {
		t.Errorf("Port override failed: %d", cfg.Port)
	}
	if cfg.Redis.Addr != "from-env:6379" {
		t.Errorf("Redis.Addr override failed: %q", cfg.Redis.Addr)
	}
}

func TestRequiredMissing(t *testing.T) {
	var cfg AppConfig
	err := load.Load(app.Schema, &cfg, load.FromEnv(map[string]string{}))
	if err == nil {
		t.Fatalf("expected required-missing error")
	}
}

func TestValidatorEnforced(t *testing.T) {
	envs := baseEnv()
	envs["PORT"] = "70000" // out of range
	var cfg AppConfig
	err := load.Load(app.Schema, &cfg, load.FromEnv(envs))
	if err == nil {
		t.Fatalf("expected validator failure")
	}
}

func TestEnvSliceAndMap(t *testing.T) {
	envs := baseEnv()
	envs["ALLOWED_HOSTS"] = "x.com, y.com ,z.com"
	envs["RATE_LIMITS"] = "read=100,write=50"

	var cfg AppConfig
	if err := load.Load(app.Schema, &cfg, load.FromEnv(envs)); err != nil {
		t.Fatalf("load: %v", err)
	}
	want := []string{"x.com", "y.com", "z.com"}
	if !reflect.DeepEqual(cfg.AllowedHosts, want) {
		t.Errorf("hosts: %v", cfg.AllowedHosts)
	}
	if cfg.RateLimits["read"] != 100 || cfg.RateLimits["write"] != 50 {
		t.Errorf("limits: %v", cfg.RateLimits)
	}
}

func TestJSONFileWithEnvOverride(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.json")
	body := []byte(`{
        "Port": 9000,
        "DSN": "postgres://file/x",
        "Redis": {"Addr": "file-redis:6379"}
    }`)
	if err := os.WriteFile(path, body, 0600); err != nil {
		t.Fatal(err)
	}

	fileSrc, err := load.FromJSONFile(path)
	if err != nil {
		t.Fatalf("FromJSONFile: %v", err)
	}

	envs := map[string]string{"REDIS_ADDR": "env-redis:6379"}

	var cfg AppConfig
	if err := load.Load(app.Schema, &cfg, fileSrc, load.FromEnv(envs)); err != nil {
		t.Fatalf("load: %v", err)
	}
	if cfg.Port != 9000 {
		t.Errorf("file Port lost: %d", cfg.Port)
	}
	if cfg.DSN != "postgres://file/x" {
		t.Errorf("file DSN: %q", cfg.DSN)
	}
	if cfg.Redis.Addr != "env-redis:6379" {
		t.Errorf("env did not override file: %q", cfg.Redis.Addr)
	}
}

func TestOptionalJSONFileMissing(t *testing.T) {
	src, err := load.FromJSONFileOptional("/nope/does/not/exist.json")
	if err != nil {
		t.Fatalf("optional missing should not error: %v", err)
	}
	var cfg AppConfig
	envs := baseEnv()
	if err := load.Load(app.Schema, &cfg, src, load.FromEnv(envs)); err != nil {
		t.Fatalf("load with empty optional: %v", err)
	}
	if cfg.Port != 8080 {
		t.Errorf("default lost: %d", cfg.Port)
	}
}

// Sanity check: a tiny ad-hoc schema with all scalar types.
func TestAllScalars(t *testing.T) {
	type Bag struct {
		I  int
		U  uint
		F  float64
		S  string
		B  bool
		D  time.Duration
		T  time.Time
		BS []byte
	}
	schema := xconf.Define("Bag",
		xconf.Int("I").Validate(validate.Positive[int]()),
		xconf.Uint("U"),
		xconf.Float64("F"),
		xconf.String("S"),
		xconf.Bool("B"),
		xconf.Duration("D"),
		xconf.Time("T"),
		xconf.Bytes("BS"),
	)
	envs := map[string]string{
		"I":  "42",
		"U":  "7",
		"F":  "1.5",
		"S":  "hi",
		"B":  "true",
		"D":  "1s",
		"T":  "2026-01-02T03:04:05Z",
		"BS": "raw",
	}
	var b Bag
	if err := load.Load(schema, &b, load.FromEnv(envs)); err != nil {
		t.Fatalf("load: %v", err)
	}
	if b.I != 42 || b.U != 7 || b.F != 1.5 || b.S != "hi" || !b.B || b.D != time.Second || string(b.BS) != "raw" {
		t.Errorf("scalar bag: %+v", b)
	}
	if b.T.Year() != 2026 {
		t.Errorf("time: %v", b.T)
	}
}
