// Code generated by xconfgen. DO NOT EDIT.

package app

import (
	"fmt"
	"github.com/gopherex/xconf/example/redislib"
	"github.com/gopherex/xconf/pkg/load"
	"os"
	"strconv"
	"strings"
	"time"
)

type AppConfig struct {
	Port         int
	DSN          string
	AllowedHosts []string
	RateLimits   map[string]int
	Redis        redislib.Config
}

// Load fills a AppConfig from the given sources by delegating to the runtime loader.
//
// Source priority: later sources override earlier ones; the schema's declared
// defaults lose to any source hit. After source-based load, any groups with
// a BindLoader are populated by calling the bound loader (its result wins).
func Load(sources ...load.Source) (*AppConfig, error) {
	cfg := &AppConfig{}
	if err := load.Load(Schema, cfg, sources...); err != nil {
		return nil, err
	}
	return cfg, nil
}

// LoadFromEnv fills a AppConfig purely from environment variables, with no
// reflection on the hot path. Schema defaults are applied first; env values
// override them. Schema validators are run via load.Validate after parsing
// (cold path: validation walks via reflection).
func LoadFromEnv() (*AppConfig, error) {
	cfg := &AppConfig{}
	var err error
	_ = err
	cfg.Port = int(8080)
	if v, ok := os.LookupEnv("PORT"); ok {
		n, perr := strconv.ParseInt(v, 10, 64)
		if perr != nil {
			return nil, perr
		}
		cfg.Port = int(n)
	}
	if v, ok := os.LookupEnv("DB_DSN"); ok {
		cfg.DSN = v
	}
	if v, ok := os.LookupEnv("ALLOWED_HOSTS"); ok {
		parts := strings.Split(v, ",")
		out := make([]string, 0, len(parts))
		for _, p := range parts {
			p = strings.TrimSpace(p)
			ev := p
			out = append(out, ev)
		}
		cfg.AllowedHosts = out
	}
	if v, ok := os.LookupEnv("RATE_LIMITS"); ok {
		out := map[string]int{}
		for _, e := range strings.Split(v, ",") {
			k, val, found := strings.Cut(strings.TrimSpace(e), "=")
			if !found {
				return nil, fmt.Errorf("malformed map entry %q", e)
			}
			kv := strings.TrimSpace(k)
			n, perr := strconv.ParseInt(strings.TrimSpace(val), 10, 64)
			if perr != nil {
				return nil, perr
			}
			vv := int(n)
			out[kv] = vv
		}
		cfg.RateLimits = out
	}
	cfg.Redis.Addr = "localhost:6379"
	if v, ok := os.LookupEnv("REDIS_ADDR"); ok {
		cfg.Redis.Addr = v
	}
	if v, ok := os.LookupEnv("REDIS_PASSWORD"); ok {
		cfg.Redis.Password = v
	}
	cfg.Redis.DB = int(0)
	if v, ok := os.LookupEnv("REDIS_DB"); ok {
		n, perr := strconv.ParseInt(v, 10, 64)
		if perr != nil {
			return nil, perr
		}
		cfg.Redis.DB = int(n)
	}
	cfg.Redis.Timeout = time.Duration(5000000000)
	if v, ok := os.LookupEnv("REDIS_TIMEOUT"); ok {
		dv, perr := time.ParseDuration(v)
		if perr != nil {
			return nil, perr
		}
		cfg.Redis.Timeout = dv
	}
	if verr := load.Validate(Schema, cfg); verr != nil {
		return nil, verr
	}
	return cfg, nil
}
